title: "Códigos e Ideias"
description: Anotações, ideias e aprendizados.
lang: pt-BR
url: "https://blog.felipecavalca.dev"
baseurl: ""
repository_url: "https://github.com/Felipe-Cavalca/blog"
timezone: America/Sao_Paulo
permalink: /posts/:title/
markdown: kramdown
highlighter: rouge
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - compose.yaml
  - vendor
